/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoluntariosRouteImport } from './routes/voluntarios'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as EmergenciasRouteImport } from './routes/emergencias'
import { Route as ConsejosRouteImport } from './routes/consejos'
import { Route as CentrosAcopioRouteImport } from './routes/centros-acopio'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AsistenteRouteImport } from './routes/asistente'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesaparecidosIndexRouteImport } from './routes/desaparecidos.index'
import { Route as AsistenteIndexRouteImport } from './routes/asistente.index'
import { Route as DesaparecidosIdRouteImport } from './routes/desaparecidos.$id'
import { Route as AsistenteThreadIdRouteImport } from './routes/asistente.$threadId'
import { Route as ApiGuideRouteImport } from './routes/api/guide'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMisReportesRouteImport } from './routes/_authenticated/mis-reportes'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicPersonasRouteImport } from './routes/api/public/personas'
import { Route as ApiPublicNoticiasRouteImport } from './routes/api/public/noticias'
import { Route as ApiPublicCentrosRouteImport } from './routes/api/public/centros'
import { Route as AuthenticatedVoluntariosRegistrarmeRouteImport } from './routes/_authenticated/voluntarios.registrarme'
import { Route as AuthenticatedDesaparecidosNuevoRouteImport } from './routes/_authenticated/desaparecidos.nuevo'
import { Route as AuthenticatedCentrosAcopioNuevoRouteImport } from './routes/_authenticated/centros-acopio.nuevo'
import { Route as AuthenticatedAdminVoluntariosRouteImport } from './routes/_authenticated/admin.voluntarios'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminNoticiasRouteImport } from './routes/_authenticated/admin.noticias'
import { Route as AuthenticatedAdminModeradoresRouteImport } from './routes/_authenticated/admin.moderadores'
import { Route as AuthenticatedAdminEmergenciasRouteImport } from './routes/_authenticated/admin.emergencias'
import { Route as AuthenticatedAdminCentrosRouteImport } from './routes/_authenticated/admin.centros'
import { Route as AuthenticatedAdminAnunciosRouteImport } from './routes/_authenticated/admin.anuncios'
import { Route as AuthenticatedDesaparecidosIdEditarRouteImport } from './routes/_authenticated/desaparecidos.$id.editar'
import { Route as AuthenticatedCentrosAcopioIdEditarRouteImport } from './routes/_authenticated/centros-acopio.$id.editar'

const VoluntariosRoute = VoluntariosRouteImport.update({
  id: '/voluntarios',
  path: '/voluntarios',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergenciasRoute = EmergenciasRouteImport.update({
  id: '/emergencias',
  path: '/emergencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsejosRoute = ConsejosRouteImport.update({
  id: '/consejos',
  path: '/consejos',
  getParentRoute: () => rootRouteImport,
} as any)
const CentrosAcopioRoute = CentrosAcopioRouteImport.update({
  id: '/centros-acopio',
  path: '/centros-acopio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteRoute = AsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesaparecidosIndexRoute = DesaparecidosIndexRouteImport.update({
  id: '/desaparecidos/',
  path: '/desaparecidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteIndexRoute = AsistenteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AsistenteRoute,
} as any)
const DesaparecidosIdRoute = DesaparecidosIdRouteImport.update({
  id: '/desaparecidos/$id',
  path: '/desaparecidos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteThreadIdRoute = AsistenteThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AsistenteRoute,
} as any)
const ApiGuideRoute = ApiGuideRouteImport.update({
  id: '/api/guide',
  path: '/api/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMisReportesRoute =
  AuthenticatedMisReportesRouteImport.update({
    id: '/mis-reportes',
    path: '/mis-reportes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPersonasRoute = ApiPublicPersonasRouteImport.update({
  id: '/api/public/personas',
  path: '/api/public/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNoticiasRoute = ApiPublicNoticiasRouteImport.update({
  id: '/api/public/noticias',
  path: '/api/public/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCentrosRoute = ApiPublicCentrosRouteImport.update({
  id: '/api/public/centros',
  path: '/api/public/centros',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoluntariosRegistrarmeRoute =
  AuthenticatedVoluntariosRegistrarmeRouteImport.update({
    id: '/voluntarios/registrarme',
    path: '/voluntarios/registrarme',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDesaparecidosNuevoRoute =
  AuthenticatedDesaparecidosNuevoRouteImport.update({
    id: '/desaparecidos/nuevo',
    path: '/desaparecidos/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCentrosAcopioNuevoRoute =
  AuthenticatedCentrosAcopioNuevoRouteImport.update({
    id: '/centros-acopio/nuevo',
    path: '/centros-acopio/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVoluntariosRoute =
  AuthenticatedAdminVoluntariosRouteImport.update({
    id: '/admin/voluntarios',
    path: '/admin/voluntarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNoticiasRoute =
  AuthenticatedAdminNoticiasRouteImport.update({
    id: '/admin/noticias',
    path: '/admin/noticias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminModeradoresRoute =
  AuthenticatedAdminModeradoresRouteImport.update({
    id: '/admin/moderadores',
    path: '/admin/moderadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmergenciasRoute =
  AuthenticatedAdminEmergenciasRouteImport.update({
    id: '/admin/emergencias',
    path: '/admin/emergencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCentrosRoute =
  AuthenticatedAdminCentrosRouteImport.update({
    id: '/admin/centros',
    path: '/admin/centros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnunciosRoute =
  AuthenticatedAdminAnunciosRouteImport.update({
    id: '/admin/anuncios',
    path: '/admin/anuncios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDesaparecidosIdEditarRoute =
  AuthenticatedDesaparecidosIdEditarRouteImport.update({
    id: '/desaparecidos/$id/editar',
    path: '/desaparecidos/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCentrosAcopioIdEditarRoute =
  AuthenticatedCentrosAcopioIdEditarRouteImport.update({
    id: '/centros-acopio/$id/editar',
    path: '/centros-acopio/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRouteWithChildren
  '/auth': typeof AuthRoute
  '/centros-acopio': typeof CentrosAcopioRoute
  '/consejos': typeof ConsejosRoute
  '/emergencias': typeof EmergenciasRoute
  '/mapa': typeof MapaRoute
  '/noticias': typeof NoticiasRoute
  '/voluntarios': typeof VoluntariosRoute
  '/mis-reportes': typeof AuthenticatedMisReportesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/api/chat': typeof ApiChatRoute
  '/api/guide': typeof ApiGuideRoute
  '/asistente/$threadId': typeof AsistenteThreadIdRoute
  '/desaparecidos/$id': typeof DesaparecidosIdRoute
  '/asistente/': typeof AsistenteIndexRoute
  '/desaparecidos/': typeof DesaparecidosIndexRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/centros': typeof AuthenticatedAdminCentrosRoute
  '/admin/emergencias': typeof AuthenticatedAdminEmergenciasRoute
  '/admin/moderadores': typeof AuthenticatedAdminModeradoresRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/voluntarios': typeof AuthenticatedAdminVoluntariosRoute
  '/centros-acopio/nuevo': typeof AuthenticatedCentrosAcopioNuevoRoute
  '/desaparecidos/nuevo': typeof AuthenticatedDesaparecidosNuevoRoute
  '/voluntarios/registrarme': typeof AuthenticatedVoluntariosRegistrarmeRoute
  '/api/public/centros': typeof ApiPublicCentrosRoute
  '/api/public/noticias': typeof ApiPublicNoticiasRoute
  '/api/public/personas': typeof ApiPublicPersonasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/centros-acopio/$id/editar': typeof AuthenticatedCentrosAcopioIdEditarRoute
  '/desaparecidos/$id/editar': typeof AuthenticatedDesaparecidosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/centros-acopio': typeof CentrosAcopioRoute
  '/consejos': typeof ConsejosRoute
  '/emergencias': typeof EmergenciasRoute
  '/mapa': typeof MapaRoute
  '/noticias': typeof NoticiasRoute
  '/voluntarios': typeof VoluntariosRoute
  '/mis-reportes': typeof AuthenticatedMisReportesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/api/chat': typeof ApiChatRoute
  '/api/guide': typeof ApiGuideRoute
  '/asistente/$threadId': typeof AsistenteThreadIdRoute
  '/desaparecidos/$id': typeof DesaparecidosIdRoute
  '/asistente': typeof AsistenteIndexRoute
  '/desaparecidos': typeof DesaparecidosIndexRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/centros': typeof AuthenticatedAdminCentrosRoute
  '/admin/emergencias': typeof AuthenticatedAdminEmergenciasRoute
  '/admin/moderadores': typeof AuthenticatedAdminModeradoresRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/voluntarios': typeof AuthenticatedAdminVoluntariosRoute
  '/centros-acopio/nuevo': typeof AuthenticatedCentrosAcopioNuevoRoute
  '/desaparecidos/nuevo': typeof AuthenticatedDesaparecidosNuevoRoute
  '/voluntarios/registrarme': typeof AuthenticatedVoluntariosRegistrarmeRoute
  '/api/public/centros': typeof ApiPublicCentrosRoute
  '/api/public/noticias': typeof ApiPublicNoticiasRoute
  '/api/public/personas': typeof ApiPublicPersonasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/centros-acopio/$id/editar': typeof AuthenticatedCentrosAcopioIdEditarRoute
  '/desaparecidos/$id/editar': typeof AuthenticatedDesaparecidosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/asistente': typeof AsistenteRouteWithChildren
  '/auth': typeof AuthRoute
  '/centros-acopio': typeof CentrosAcopioRoute
  '/consejos': typeof ConsejosRoute
  '/emergencias': typeof EmergenciasRoute
  '/mapa': typeof MapaRoute
  '/noticias': typeof NoticiasRoute
  '/voluntarios': typeof VoluntariosRoute
  '/_authenticated/mis-reportes': typeof AuthenticatedMisReportesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/api/chat': typeof ApiChatRoute
  '/api/guide': typeof ApiGuideRoute
  '/asistente/$threadId': typeof AsistenteThreadIdRoute
  '/desaparecidos/$id': typeof DesaparecidosIdRoute
  '/asistente/': typeof AsistenteIndexRoute
  '/desaparecidos/': typeof DesaparecidosIndexRoute
  '/_authenticated/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/_authenticated/admin/centros': typeof AuthenticatedAdminCentrosRoute
  '/_authenticated/admin/emergencias': typeof AuthenticatedAdminEmergenciasRoute
  '/_authenticated/admin/moderadores': typeof AuthenticatedAdminModeradoresRoute
  '/_authenticated/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/voluntarios': typeof AuthenticatedAdminVoluntariosRoute
  '/_authenticated/centros-acopio/nuevo': typeof AuthenticatedCentrosAcopioNuevoRoute
  '/_authenticated/desaparecidos/nuevo': typeof AuthenticatedDesaparecidosNuevoRoute
  '/_authenticated/voluntarios/registrarme': typeof AuthenticatedVoluntariosRegistrarmeRoute
  '/api/public/centros': typeof ApiPublicCentrosRoute
  '/api/public/noticias': typeof ApiPublicNoticiasRoute
  '/api/public/personas': typeof ApiPublicPersonasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/centros-acopio/$id/editar': typeof AuthenticatedCentrosAcopioIdEditarRoute
  '/_authenticated/desaparecidos/$id/editar': typeof AuthenticatedDesaparecidosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asistente'
    | '/auth'
    | '/centros-acopio'
    | '/consejos'
    | '/emergencias'
    | '/mapa'
    | '/noticias'
    | '/voluntarios'
    | '/mis-reportes'
    | '/perfil'
    | '/api/chat'
    | '/api/guide'
    | '/asistente/$threadId'
    | '/desaparecidos/$id'
    | '/asistente/'
    | '/desaparecidos/'
    | '/admin/anuncios'
    | '/admin/centros'
    | '/admin/emergencias'
    | '/admin/moderadores'
    | '/admin/noticias'
    | '/admin/usuarios'
    | '/admin/voluntarios'
    | '/centros-acopio/nuevo'
    | '/desaparecidos/nuevo'
    | '/voluntarios/registrarme'
    | '/api/public/centros'
    | '/api/public/noticias'
    | '/api/public/personas'
    | '/admin/'
    | '/centros-acopio/$id/editar'
    | '/desaparecidos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/centros-acopio'
    | '/consejos'
    | '/emergencias'
    | '/mapa'
    | '/noticias'
    | '/voluntarios'
    | '/mis-reportes'
    | '/perfil'
    | '/api/chat'
    | '/api/guide'
    | '/asistente/$threadId'
    | '/desaparecidos/$id'
    | '/asistente'
    | '/desaparecidos'
    | '/admin/anuncios'
    | '/admin/centros'
    | '/admin/emergencias'
    | '/admin/moderadores'
    | '/admin/noticias'
    | '/admin/usuarios'
    | '/admin/voluntarios'
    | '/centros-acopio/nuevo'
    | '/desaparecidos/nuevo'
    | '/voluntarios/registrarme'
    | '/api/public/centros'
    | '/api/public/noticias'
    | '/api/public/personas'
    | '/admin'
    | '/centros-acopio/$id/editar'
    | '/desaparecidos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/asistente'
    | '/auth'
    | '/centros-acopio'
    | '/consejos'
    | '/emergencias'
    | '/mapa'
    | '/noticias'
    | '/voluntarios'
    | '/_authenticated/mis-reportes'
    | '/_authenticated/perfil'
    | '/api/chat'
    | '/api/guide'
    | '/asistente/$threadId'
    | '/desaparecidos/$id'
    | '/asistente/'
    | '/desaparecidos/'
    | '/_authenticated/admin/anuncios'
    | '/_authenticated/admin/centros'
    | '/_authenticated/admin/emergencias'
    | '/_authenticated/admin/moderadores'
    | '/_authenticated/admin/noticias'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/voluntarios'
    | '/_authenticated/centros-acopio/nuevo'
    | '/_authenticated/desaparecidos/nuevo'
    | '/_authenticated/voluntarios/registrarme'
    | '/api/public/centros'
    | '/api/public/noticias'
    | '/api/public/personas'
    | '/_authenticated/admin/'
    | '/_authenticated/centros-acopio/$id/editar'
    | '/_authenticated/desaparecidos/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AsistenteRoute: typeof AsistenteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CentrosAcopioRoute: typeof CentrosAcopioRoute
  ConsejosRoute: typeof ConsejosRoute
  EmergenciasRoute: typeof EmergenciasRoute
  MapaRoute: typeof MapaRoute
  NoticiasRoute: typeof NoticiasRoute
  VoluntariosRoute: typeof VoluntariosRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGuideRoute: typeof ApiGuideRoute
  DesaparecidosIdRoute: typeof DesaparecidosIdRoute
  DesaparecidosIndexRoute: typeof DesaparecidosIndexRoute
  ApiPublicCentrosRoute: typeof ApiPublicCentrosRoute
  ApiPublicNoticiasRoute: typeof ApiPublicNoticiasRoute
  ApiPublicPersonasRoute: typeof ApiPublicPersonasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voluntarios': {
      id: '/voluntarios'
      path: '/voluntarios'
      fullPath: '/voluntarios'
      preLoaderRoute: typeof VoluntariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergencias': {
      id: '/emergencias'
      path: '/emergencias'
      fullPath: '/emergencias'
      preLoaderRoute: typeof EmergenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consejos': {
      id: '/consejos'
      path: '/consejos'
      fullPath: '/consejos'
      preLoaderRoute: typeof ConsejosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centros-acopio': {
      id: '/centros-acopio'
      path: '/centros-acopio'
      fullPath: '/centros-acopio'
      preLoaderRoute: typeof CentrosAcopioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente': {
      id: '/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AsistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desaparecidos/': {
      id: '/desaparecidos/'
      path: '/desaparecidos'
      fullPath: '/desaparecidos/'
      preLoaderRoute: typeof DesaparecidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente/': {
      id: '/asistente/'
      path: '/'
      fullPath: '/asistente/'
      preLoaderRoute: typeof AsistenteIndexRouteImport
      parentRoute: typeof AsistenteRoute
    }
    '/desaparecidos/$id': {
      id: '/desaparecidos/$id'
      path: '/desaparecidos/$id'
      fullPath: '/desaparecidos/$id'
      preLoaderRoute: typeof DesaparecidosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente/$threadId': {
      id: '/asistente/$threadId'
      path: '/$threadId'
      fullPath: '/asistente/$threadId'
      preLoaderRoute: typeof AsistenteThreadIdRouteImport
      parentRoute: typeof AsistenteRoute
    }
    '/api/guide': {
      id: '/api/guide'
      path: '/api/guide'
      fullPath: '/api/guide'
      preLoaderRoute: typeof ApiGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-reportes': {
      id: '/_authenticated/mis-reportes'
      path: '/mis-reportes'
      fullPath: '/mis-reportes'
      preLoaderRoute: typeof AuthenticatedMisReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/personas': {
      id: '/api/public/personas'
      path: '/api/public/personas'
      fullPath: '/api/public/personas'
      preLoaderRoute: typeof ApiPublicPersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/noticias': {
      id: '/api/public/noticias'
      path: '/api/public/noticias'
      fullPath: '/api/public/noticias'
      preLoaderRoute: typeof ApiPublicNoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/centros': {
      id: '/api/public/centros'
      path: '/api/public/centros'
      fullPath: '/api/public/centros'
      preLoaderRoute: typeof ApiPublicCentrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voluntarios/registrarme': {
      id: '/_authenticated/voluntarios/registrarme'
      path: '/voluntarios/registrarme'
      fullPath: '/voluntarios/registrarme'
      preLoaderRoute: typeof AuthenticatedVoluntariosRegistrarmeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desaparecidos/nuevo': {
      id: '/_authenticated/desaparecidos/nuevo'
      path: '/desaparecidos/nuevo'
      fullPath: '/desaparecidos/nuevo'
      preLoaderRoute: typeof AuthenticatedDesaparecidosNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centros-acopio/nuevo': {
      id: '/_authenticated/centros-acopio/nuevo'
      path: '/centros-acopio/nuevo'
      fullPath: '/centros-acopio/nuevo'
      preLoaderRoute: typeof AuthenticatedCentrosAcopioNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/voluntarios': {
      id: '/_authenticated/admin/voluntarios'
      path: '/admin/voluntarios'
      fullPath: '/admin/voluntarios'
      preLoaderRoute: typeof AuthenticatedAdminVoluntariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/noticias': {
      id: '/_authenticated/admin/noticias'
      path: '/admin/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AuthenticatedAdminNoticiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/moderadores': {
      id: '/_authenticated/admin/moderadores'
      path: '/admin/moderadores'
      fullPath: '/admin/moderadores'
      preLoaderRoute: typeof AuthenticatedAdminModeradoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/emergencias': {
      id: '/_authenticated/admin/emergencias'
      path: '/admin/emergencias'
      fullPath: '/admin/emergencias'
      preLoaderRoute: typeof AuthenticatedAdminEmergenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/centros': {
      id: '/_authenticated/admin/centros'
      path: '/admin/centros'
      fullPath: '/admin/centros'
      preLoaderRoute: typeof AuthenticatedAdminCentrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/anuncios': {
      id: '/_authenticated/admin/anuncios'
      path: '/admin/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AuthenticatedAdminAnunciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desaparecidos/$id/editar': {
      id: '/_authenticated/desaparecidos/$id/editar'
      path: '/desaparecidos/$id/editar'
      fullPath: '/desaparecidos/$id/editar'
      preLoaderRoute: typeof AuthenticatedDesaparecidosIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centros-acopio/$id/editar': {
      id: '/_authenticated/centros-acopio/$id/editar'
      path: '/centros-acopio/$id/editar'
      fullPath: '/centros-acopio/$id/editar'
      preLoaderRoute: typeof AuthenticatedCentrosAcopioIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMisReportesRoute: typeof AuthenticatedMisReportesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedAdminAnunciosRoute: typeof AuthenticatedAdminAnunciosRoute
  AuthenticatedAdminCentrosRoute: typeof AuthenticatedAdminCentrosRoute
  AuthenticatedAdminEmergenciasRoute: typeof AuthenticatedAdminEmergenciasRoute
  AuthenticatedAdminModeradoresRoute: typeof AuthenticatedAdminModeradoresRoute
  AuthenticatedAdminNoticiasRoute: typeof AuthenticatedAdminNoticiasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminVoluntariosRoute: typeof AuthenticatedAdminVoluntariosRoute
  AuthenticatedCentrosAcopioNuevoRoute: typeof AuthenticatedCentrosAcopioNuevoRoute
  AuthenticatedDesaparecidosNuevoRoute: typeof AuthenticatedDesaparecidosNuevoRoute
  AuthenticatedVoluntariosRegistrarmeRoute: typeof AuthenticatedVoluntariosRegistrarmeRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedCentrosAcopioIdEditarRoute: typeof AuthenticatedCentrosAcopioIdEditarRoute
  AuthenticatedDesaparecidosIdEditarRoute: typeof AuthenticatedDesaparecidosIdEditarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMisReportesRoute: AuthenticatedMisReportesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedAdminAnunciosRoute: AuthenticatedAdminAnunciosRoute,
  AuthenticatedAdminCentrosRoute: AuthenticatedAdminCentrosRoute,
  AuthenticatedAdminEmergenciasRoute: AuthenticatedAdminEmergenciasRoute,
  AuthenticatedAdminModeradoresRoute: AuthenticatedAdminModeradoresRoute,
  AuthenticatedAdminNoticiasRoute: AuthenticatedAdminNoticiasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminVoluntariosRoute: AuthenticatedAdminVoluntariosRoute,
  AuthenticatedCentrosAcopioNuevoRoute: AuthenticatedCentrosAcopioNuevoRoute,
  AuthenticatedDesaparecidosNuevoRoute: AuthenticatedDesaparecidosNuevoRoute,
  AuthenticatedVoluntariosRegistrarmeRoute:
    AuthenticatedVoluntariosRegistrarmeRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedCentrosAcopioIdEditarRoute:
    AuthenticatedCentrosAcopioIdEditarRoute,
  AuthenticatedDesaparecidosIdEditarRoute:
    AuthenticatedDesaparecidosIdEditarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AsistenteRouteChildren {
  AsistenteThreadIdRoute: typeof AsistenteThreadIdRoute
  AsistenteIndexRoute: typeof AsistenteIndexRoute
}

const AsistenteRouteChildren: AsistenteRouteChildren = {
  AsistenteThreadIdRoute: AsistenteThreadIdRoute,
  AsistenteIndexRoute: AsistenteIndexRoute,
}

const AsistenteRouteWithChildren = AsistenteRoute._addFileChildren(
  AsistenteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AsistenteRoute: AsistenteRouteWithChildren,
  AuthRoute: AuthRoute,
  CentrosAcopioRoute: CentrosAcopioRoute,
  ConsejosRoute: ConsejosRoute,
  EmergenciasRoute: EmergenciasRoute,
  MapaRoute: MapaRoute,
  NoticiasRoute: NoticiasRoute,
  VoluntariosRoute: VoluntariosRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGuideRoute: ApiGuideRoute,
  DesaparecidosIdRoute: DesaparecidosIdRoute,
  DesaparecidosIndexRoute: DesaparecidosIndexRoute,
  ApiPublicCentrosRoute: ApiPublicCentrosRoute,
  ApiPublicNoticiasRoute: ApiPublicNoticiasRoute,
  ApiPublicPersonasRoute: ApiPublicPersonasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
