/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoluntariosRouteImport } from './routes/voluntarios'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as EmergenciasRouteImport } from './routes/emergencias'
import { Route as DesaparecidosRouteImport } from './routes/desaparecidos'
import { Route as CentrosAcopioRouteImport } from './routes/centros-acopio'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesaparecidosIdRouteImport } from './routes/desaparecidos.$id'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMisReportesRouteImport } from './routes/_authenticated/mis-reportes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedVoluntariosRegistrarmeRouteImport } from './routes/_authenticated/voluntarios.registrarme'
import { Route as AuthenticatedDesaparecidosNuevoRouteImport } from './routes/_authenticated/desaparecidos.nuevo'
import { Route as AuthenticatedCentrosAcopioNuevoRouteImport } from './routes/_authenticated/centros-acopio.nuevo'
import { Route as AuthenticatedAdminNoticiasRouteImport } from './routes/_authenticated/admin.noticias'
import { Route as AuthenticatedAdminEmergenciasRouteImport } from './routes/_authenticated/admin.emergencias'
import { Route as AuthenticatedAdminCentrosRouteImport } from './routes/_authenticated/admin.centros'
import { Route as AuthenticatedAdminAnunciosRouteImport } from './routes/_authenticated/admin.anuncios'

const VoluntariosRoute = VoluntariosRouteImport.update({
  id: '/voluntarios',
  path: '/voluntarios',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergenciasRoute = EmergenciasRouteImport.update({
  id: '/emergencias',
  path: '/emergencias',
  getParentRoute: () => rootRouteImport,
} as any)
const DesaparecidosRoute = DesaparecidosRouteImport.update({
  id: '/desaparecidos',
  path: '/desaparecidos',
  getParentRoute: () => rootRouteImport,
} as any)
const CentrosAcopioRoute = CentrosAcopioRouteImport.update({
  id: '/centros-acopio',
  path: '/centros-acopio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesaparecidosIdRoute = DesaparecidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DesaparecidosRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMisReportesRoute =
  AuthenticatedMisReportesRouteImport.update({
    id: '/mis-reportes',
    path: '/mis-reportes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVoluntariosRegistrarmeRoute =
  AuthenticatedVoluntariosRegistrarmeRouteImport.update({
    id: '/voluntarios/registrarme',
    path: '/voluntarios/registrarme',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDesaparecidosNuevoRoute =
  AuthenticatedDesaparecidosNuevoRouteImport.update({
    id: '/desaparecidos/nuevo',
    path: '/desaparecidos/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCentrosAcopioNuevoRoute =
  AuthenticatedCentrosAcopioNuevoRouteImport.update({
    id: '/centros-acopio/nuevo',
    path: '/centros-acopio/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNoticiasRoute =
  AuthenticatedAdminNoticiasRouteImport.update({
    id: '/noticias',
    path: '/noticias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmergenciasRoute =
  AuthenticatedAdminEmergenciasRouteImport.update({
    id: '/emergencias',
    path: '/emergencias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCentrosRoute =
  AuthenticatedAdminCentrosRouteImport.update({
    id: '/centros',
    path: '/centros',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnunciosRoute =
  AuthenticatedAdminAnunciosRouteImport.update({
    id: '/anuncios',
    path: '/anuncios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/centros-acopio': typeof CentrosAcopioRoute
  '/desaparecidos': typeof DesaparecidosRouteWithChildren
  '/emergencias': typeof EmergenciasRoute
  '/mapa': typeof MapaRoute
  '/noticias': typeof NoticiasRoute
  '/voluntarios': typeof VoluntariosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/mis-reportes': typeof AuthenticatedMisReportesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/desaparecidos/$id': typeof DesaparecidosIdRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/centros': typeof AuthenticatedAdminCentrosRoute
  '/admin/emergencias': typeof AuthenticatedAdminEmergenciasRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/centros-acopio/nuevo': typeof AuthenticatedCentrosAcopioNuevoRoute
  '/desaparecidos/nuevo': typeof AuthenticatedDesaparecidosNuevoRoute
  '/voluntarios/registrarme': typeof AuthenticatedVoluntariosRegistrarmeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/centros-acopio': typeof CentrosAcopioRoute
  '/desaparecidos': typeof DesaparecidosRouteWithChildren
  '/emergencias': typeof EmergenciasRoute
  '/mapa': typeof MapaRoute
  '/noticias': typeof NoticiasRoute
  '/voluntarios': typeof VoluntariosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/mis-reportes': typeof AuthenticatedMisReportesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/desaparecidos/$id': typeof DesaparecidosIdRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/centros': typeof AuthenticatedAdminCentrosRoute
  '/admin/emergencias': typeof AuthenticatedAdminEmergenciasRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/centros-acopio/nuevo': typeof AuthenticatedCentrosAcopioNuevoRoute
  '/desaparecidos/nuevo': typeof AuthenticatedDesaparecidosNuevoRoute
  '/voluntarios/registrarme': typeof AuthenticatedVoluntariosRegistrarmeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/centros-acopio': typeof CentrosAcopioRoute
  '/desaparecidos': typeof DesaparecidosRouteWithChildren
  '/emergencias': typeof EmergenciasRoute
  '/mapa': typeof MapaRoute
  '/noticias': typeof NoticiasRoute
  '/voluntarios': typeof VoluntariosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/mis-reportes': typeof AuthenticatedMisReportesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/desaparecidos/$id': typeof DesaparecidosIdRoute
  '/_authenticated/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/_authenticated/admin/centros': typeof AuthenticatedAdminCentrosRoute
  '/_authenticated/admin/emergencias': typeof AuthenticatedAdminEmergenciasRoute
  '/_authenticated/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/_authenticated/centros-acopio/nuevo': typeof AuthenticatedCentrosAcopioNuevoRoute
  '/_authenticated/desaparecidos/nuevo': typeof AuthenticatedDesaparecidosNuevoRoute
  '/_authenticated/voluntarios/registrarme': typeof AuthenticatedVoluntariosRegistrarmeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/centros-acopio'
    | '/desaparecidos'
    | '/emergencias'
    | '/mapa'
    | '/noticias'
    | '/voluntarios'
    | '/admin'
    | '/mis-reportes'
    | '/perfil'
    | '/desaparecidos/$id'
    | '/admin/anuncios'
    | '/admin/centros'
    | '/admin/emergencias'
    | '/admin/noticias'
    | '/centros-acopio/nuevo'
    | '/desaparecidos/nuevo'
    | '/voluntarios/registrarme'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/centros-acopio'
    | '/desaparecidos'
    | '/emergencias'
    | '/mapa'
    | '/noticias'
    | '/voluntarios'
    | '/admin'
    | '/mis-reportes'
    | '/perfil'
    | '/desaparecidos/$id'
    | '/admin/anuncios'
    | '/admin/centros'
    | '/admin/emergencias'
    | '/admin/noticias'
    | '/centros-acopio/nuevo'
    | '/desaparecidos/nuevo'
    | '/voluntarios/registrarme'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/centros-acopio'
    | '/desaparecidos'
    | '/emergencias'
    | '/mapa'
    | '/noticias'
    | '/voluntarios'
    | '/_authenticated/admin'
    | '/_authenticated/mis-reportes'
    | '/_authenticated/perfil'
    | '/desaparecidos/$id'
    | '/_authenticated/admin/anuncios'
    | '/_authenticated/admin/centros'
    | '/_authenticated/admin/emergencias'
    | '/_authenticated/admin/noticias'
    | '/_authenticated/centros-acopio/nuevo'
    | '/_authenticated/desaparecidos/nuevo'
    | '/_authenticated/voluntarios/registrarme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CentrosAcopioRoute: typeof CentrosAcopioRoute
  DesaparecidosRoute: typeof DesaparecidosRouteWithChildren
  EmergenciasRoute: typeof EmergenciasRoute
  MapaRoute: typeof MapaRoute
  NoticiasRoute: typeof NoticiasRoute
  VoluntariosRoute: typeof VoluntariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voluntarios': {
      id: '/voluntarios'
      path: '/voluntarios'
      fullPath: '/voluntarios'
      preLoaderRoute: typeof VoluntariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergencias': {
      id: '/emergencias'
      path: '/emergencias'
      fullPath: '/emergencias'
      preLoaderRoute: typeof EmergenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desaparecidos': {
      id: '/desaparecidos'
      path: '/desaparecidos'
      fullPath: '/desaparecidos'
      preLoaderRoute: typeof DesaparecidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centros-acopio': {
      id: '/centros-acopio'
      path: '/centros-acopio'
      fullPath: '/centros-acopio'
      preLoaderRoute: typeof CentrosAcopioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desaparecidos/$id': {
      id: '/desaparecidos/$id'
      path: '/$id'
      fullPath: '/desaparecidos/$id'
      preLoaderRoute: typeof DesaparecidosIdRouteImport
      parentRoute: typeof DesaparecidosRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-reportes': {
      id: '/_authenticated/mis-reportes'
      path: '/mis-reportes'
      fullPath: '/mis-reportes'
      preLoaderRoute: typeof AuthenticatedMisReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/voluntarios/registrarme': {
      id: '/_authenticated/voluntarios/registrarme'
      path: '/voluntarios/registrarme'
      fullPath: '/voluntarios/registrarme'
      preLoaderRoute: typeof AuthenticatedVoluntariosRegistrarmeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desaparecidos/nuevo': {
      id: '/_authenticated/desaparecidos/nuevo'
      path: '/desaparecidos/nuevo'
      fullPath: '/desaparecidos/nuevo'
      preLoaderRoute: typeof AuthenticatedDesaparecidosNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centros-acopio/nuevo': {
      id: '/_authenticated/centros-acopio/nuevo'
      path: '/centros-acopio/nuevo'
      fullPath: '/centros-acopio/nuevo'
      preLoaderRoute: typeof AuthenticatedCentrosAcopioNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/noticias': {
      id: '/_authenticated/admin/noticias'
      path: '/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AuthenticatedAdminNoticiasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/emergencias': {
      id: '/_authenticated/admin/emergencias'
      path: '/emergencias'
      fullPath: '/admin/emergencias'
      preLoaderRoute: typeof AuthenticatedAdminEmergenciasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/centros': {
      id: '/_authenticated/admin/centros'
      path: '/centros'
      fullPath: '/admin/centros'
      preLoaderRoute: typeof AuthenticatedAdminCentrosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/anuncios': {
      id: '/_authenticated/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AuthenticatedAdminAnunciosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnunciosRoute: typeof AuthenticatedAdminAnunciosRoute
  AuthenticatedAdminCentrosRoute: typeof AuthenticatedAdminCentrosRoute
  AuthenticatedAdminEmergenciasRoute: typeof AuthenticatedAdminEmergenciasRoute
  AuthenticatedAdminNoticiasRoute: typeof AuthenticatedAdminNoticiasRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnunciosRoute: AuthenticatedAdminAnunciosRoute,
  AuthenticatedAdminCentrosRoute: AuthenticatedAdminCentrosRoute,
  AuthenticatedAdminEmergenciasRoute: AuthenticatedAdminEmergenciasRoute,
  AuthenticatedAdminNoticiasRoute: AuthenticatedAdminNoticiasRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMisReportesRoute: typeof AuthenticatedMisReportesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedCentrosAcopioNuevoRoute: typeof AuthenticatedCentrosAcopioNuevoRoute
  AuthenticatedDesaparecidosNuevoRoute: typeof AuthenticatedDesaparecidosNuevoRoute
  AuthenticatedVoluntariosRegistrarmeRoute: typeof AuthenticatedVoluntariosRegistrarmeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMisReportesRoute: AuthenticatedMisReportesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedCentrosAcopioNuevoRoute: AuthenticatedCentrosAcopioNuevoRoute,
  AuthenticatedDesaparecidosNuevoRoute: AuthenticatedDesaparecidosNuevoRoute,
  AuthenticatedVoluntariosRegistrarmeRoute:
    AuthenticatedVoluntariosRegistrarmeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DesaparecidosRouteChildren {
  DesaparecidosIdRoute: typeof DesaparecidosIdRoute
}

const DesaparecidosRouteChildren: DesaparecidosRouteChildren = {
  DesaparecidosIdRoute: DesaparecidosIdRoute,
}

const DesaparecidosRouteWithChildren = DesaparecidosRoute._addFileChildren(
  DesaparecidosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CentrosAcopioRoute: CentrosAcopioRoute,
  DesaparecidosRoute: DesaparecidosRouteWithChildren,
  EmergenciasRoute: EmergenciasRoute,
  MapaRoute: MapaRoute,
  NoticiasRoute: NoticiasRoute,
  VoluntariosRoute: VoluntariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
